In [14]:
import pandas as pd
import numpy as np
import csv
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds',
'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
client = gspread.authorize(creds)

# open the google sheets
pendulum_1 = client.open('pendulum1GoodMeasurementsCalculations').sheet1

pendulum_2 = client.open('pendulum2GoodMeasurementsCalculations').sheet1

#read in the data from the spreadsheet
pendulum_1_data = pendulum_1.get_all_values()

pendulum_2_data = pendulum_2.get_all_values()

# make a pandas dataframe out of the data
pendulum_1_df = pd.DataFrame(pendulum_1_data[1:], columns = pendulum_1_data[0])

pendulum_2_df = pd.DataFrame(pendulum_2_data[1:], columns = pendulum_2_data[0])


# print out the data from one of the sheets as an example
pendulum_2_df

   Trial    Time Counts knife edge brass mass plastic mass
0      1  300.66    316     10.967     42.914       68.713
1      2  300.63    316     10.967     42.914       68.713
2      3  300.72    316     10.967     42.914       68.713
3      4  300.72    316     10.967     42.914       68.713
4      5  300.62    316     10.967     42.914       68.713
5      6  300.63    316     10.967     42.914       68.713
6      7  300.69    316     10.967     42.914       68.713
7      8   298.5    314     10.967     42.914       68.713
8      9  302.56    318     10.967     42.914       68.713
9     10  300.84    316     10.967     42.914       68.713
10    11   321.6    338     10.967     42.914       68.713
11    12  302.75    318     10.967     42.914       68.713
12    13  300.82    316     10.967     42.914       68.713
13    14  298.57    314     10.967     42.914       68.713
14    15  298.56    314     10.967     42.914       68.713
15    16  308.22    324     10.967     42.914       68.713
16    17  304.47    320     10.967     42.914       68.713
17    18  298.72    314     10.967     42.914       68.713
18    19  302.66    318     10.967     42.914       68.713
19    20  300.69    316     10.967     42.914       68.713
20    21  300.59    316     10.967     42.914       68.713
21    22  304.81    320     10.967     42.914       68.713
22    23  300.69    316     10.967     42.914       68.713
23    24  298.75    314     10.967     42.914       68.713
24    25  302.57    318     10.967     42.914       68.713
25    26  308.34    324     10.967     42.914       68.713
26    27  304.66    320     10.967     42.914       68.713
27    28  312.35    328     10.967     42.914       68.713
28    29  302.66    318     10.967     42.914       68.713
29    30  298.66    314     10.967     42.914       68.713
30    31  300.66    316     10.967     42.914       68.713
31    32  306.41    322     10.967     42.914       68.713
32    33   294.9    310     10.967     42.914       68.713
33    34  300.71    316     10.967     42.914       68.713
34    35  300.75    316     10.967     42.914       68.713
35    36  300.75    316     10.967     42.914       68.713
36    37  304.59    320     10.967     42.914       68.713
37    38  304.66    320     10.967     42.914       68.713
38    39  304.53    320     10.967     42.914       68.713
39    40  298.81    314     10.967     42.914       68.713
40    41  298.97    314     10.967     42.914       68.713
41    42  302.66    318     10.967     42.914       68.713
42    43  300.69    316     10.967     42.914       68.713
43    44  302.81    318     10.967     42.914       68.713
44    45  300.56    316     10.967     42.914       68.713
45    46  302.41    318     10.967     42.914       68.713
46    47  298.72    314     10.967     42.914       68.713
47    48     295    310     10.967     42.914       68.713
48    49  300.69    316     10.967     42.914       68.713
49    50  300.75    316     10.967     42.914       68.713

In [15]:
# Convert the Time and Counts columns to numeric values
pendulum_2_df['Time'] = pd.to_numeric(pendulum_2_df['Time'])
pendulum_2_df['Counts'] = pd.to_numeric(pendulum_2_df['Counts'])

pendulum_1_df['Time'] = pd.to_numeric(pendulum_1_df['Time'])
pendulum_1_df['Counts'] = pd.to_numeric(pendulum_1_df['Counts'])

In [16]:
# Calculate the period of each trial for each pendulum
pendulum_1_df['Period'] = pendulum_1_df['Time'] / (pendulum_1_df['Counts'] / 2)

pendulum_2_df['Period'] = pendulum_2_df['Time'] / (pendulum_2_df['Counts'] / 2)

# calculate the standard deviation of each pendulum
std_period1 = pendulum_1_df.loc[:,"Period"].std()

std_period2 = pendulum_2_df.loc[:,"Period"].std()

# Calculate the mean of each pendulum
mean_period1 = pendulum_1_df.loc[:,"Period"].mean()

mean_period2 = pendulum_2_df.loc[:,"Period"].mean()

# print out the mean and error of each period
print("Period1: " + str(mean_period1))

print("Period2: " + str(mean_period2))

print("Period1 error: " + str(std_period1/np.sqrt(50)))

print("Period2 error: " + str(std_period2/np.sqrt(50)))

Period1: 1.90251632015529
Period2: 1.9031536058307212
Period1 error: 8.400437814259619e-05
Period2 error: 0.000105541906951631

In [21]:
# convert the Period columns to a list
period_1 = pendulum_1_df['Period'].tolist()

period_2 = pendulum_2_df['Period'].tolist()

print(period_1)

[1.9026582278481012, 1.9031012658227848, 1.9029113924050634, 1.9024683544303795, 1.9027215189873417, 1.9023417721518987, 1.9018987341772151, 1.9015189873417722, 1.9031012658227848, 1.9029113924050634, 1.9022784810126583, 1.9034810126582278, 1.9030379746835444, 1.9032911392405065, 1.9033333333333333, 1.9017610062893082, 1.9025625000000002, 1.9024683544303795, 1.902919254658385, 1.9030817610062891, 1.9027044025157231, 1.9025157232704402, 1.9027215189873417, 1.9027215189873417, 1.9021383647798742, 1.9019496855345914, 1.9027044025157231, 1.9024683544303795, 1.900943396226415, 1.9023270440251574, 1.9015189873417722, 1.9031012658227848, 1.9026582278481012, 1.9034810126582278, 1.9027215189873417, 1.9020886075949366, 1.9025316455696204, 1.9020886075949366, 1.9022784810126583, 1.9027672955974844, 1.9017499999999998, 1.902919254658385, 1.9027044025157231, 1.9021739130434783, 1.9025157232704402, 1.9032704402515723, 1.9022929936305735, 1.9021383647798742, 1.903076923076923, 1.9006962025316456]

In [22]:
# add the period column to the pendulum 1 Google Sheet
pendulum_1.update_cell(1, 7, 'Period')
for row_index, curr_period in enumerate(period_1):
    pendulum_1.update_cell(row_index + 2, 7, curr_period)

In [23]:
# add the period column to the pendulum 2 Google Sheet
pendulum_2.update_cell(1, 7, 'Period')
for row_index, curr_period in enumerate(period_2):
    pendulum_2.update_cell(row_index + 2, 7, curr_period)

In [25]:
# Add the mean and error in mean calculations to the google sheets.
pendulum_1.update_cell(52, 1, 'Period Mean')
pendulum_1.update_cell(52, 7, mean_period1)
pendulum_1.update_cell(53, 1, 'Error in Mean')
pendulum_1.update_cell(53, 7, std_period1/np.sqrt(50))

pendulum_2.update_cell(52, 1, 'Period Mean')
pendulum_2.update_cell(52, 7, mean_period2)
pendulum_2.update_cell(53, 1, 'Error in Mean')
pendulum_2.update_cell(53, 7, std_period2/np.sqrt(50))

{'spreadsheetId': '1na8RGh9m5ivkRcamO9_qb3UvVCvOcPqTlV-CDOGfp_o',
 'updatedRange': 'Sheet1!G53',
 'updatedRows': 1,
 'updatedColumns': 1,
 'updatedCells': 1}